### PR TITLE
carbon: size the banner image appropriately

### LINKED ISSUE #1702: [klima data] What is digital carbon? page design breaks on wider screens
This page: https://carbon-git-staging-klimadao.vercel.app/overview/digital-carbon

Issue:
- On wider monitor screens, the banner image is not stretching the full screen width so the page layout looks wrong.

Screenshot 2023-10-17 at 2 59 58 PM

### PR DESCRIPTION
**Pull request by sprrwhwk**
## Description

This PR makes the banner image stretch. Note that it looks strange on mobile and very wide screens since it's not a vector image @jabby09.

## Related Ticket

Resolves #1702

## Checklist

- [x] I have run `npm run build-all` without errors
- [x] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

**Review by jabby09 — CHANGES_REQUESTED** [review]
@sprrwhwk okay, stretching the image is not going to work especially if it just introduces issues on other screen size

@theprofessora can you help us source/create a proper banner image we can use across various screen width sizes?

**Comment by biwano** [comment]
@sprrwhwk  Not sure if it helps but I remember coding that: https://github.com/KlimaDAO/klimadao/blob/staging/lib/utils/getImageSizes/index.ts

It adds properties to the Image component so that the nextJS server sends images whose sizes depends on the viewport.
see: https://nextjs.org/docs/pages/api-reference/components/image#sizes

**Comment by theprofessora** [comment]
Does this not work?

```
.cover-img {
    width: 100%;
    height: auto;
    object-fit: contain;
}
```

and then place that img in a container that responsively resizes?

```
.cover-img-container {
   max-width: 1132px;
   padding: 40px;
}
```

**Comment by sprrwhwk** [comment]
@theprofessora it would look like this on desktop:
grafik

and like this on mobile:
grafik

WDYT?

**Comment by sprrwhwk** [comment]
I think it looks great now 👍

**Review by jabby09 — APPROVED** [review]

**Pull request merged**
