### PR TITLE
Makka / #1741 add disclaimer modal

### LINKED ISSUE #1741: [klima app] Disclaimer text for $KLIMA token
We will need a disclaimer put onto the KlimaDAO dApp due to new UK regulations.

Note not required for Carbonmark.

Needs to appear at a minimum on these pages:
https://app.klimadao.finance/#/buy
https://app.klimadao.finance/#/stake
https://app.klimadao.finance/#/bonds
https://app.klimadao.finance/#/wrap

User needs to be presented with the disclaimer text when they open a new session. Within a browser session, once they dismiss the message not required to be shown again.

One option might be a popup like:
image

Disclaimer text required below:

> Investment Risk Disclaimer
> 
> Purchasing cryptocurrencies, including the $KLIMA token, involves a high degree of risk and should be considered extremely speculative. Here are some important points to consider:
> 
> Loss of Investment: The value of $KLIMA and other cryptocurrencies can rapidly increase or decrease at any time. As a result, you could experience significant and rapid losses, including the loss of all money invested.
> 
> Lack of Liquidity: There may be no active market for $KLIMA, which may result in losses if you need to sell your tokens quickly.
> 
> Regulatory Actions and Changes: The regulatory environment for cryptocurrencies is evolving and changes in regulation could adversely affect your investment.
> 
> Operational Risks: The KlimaDAO platform relies on various technologies related to the Polygon network and other digital assets. These technologies are subject to change, and such changes could adversely affect your investment.
> 
> No Guarantee: There is no guarantee that the KlimaDAO platform or the $KLIMA token will achieve its objectives or that any value will be retained in the Protocol.
> 
> This summary risk warning does not disclose all the risks associated with investing in $KLIMA. You should conduct your own due diligence and consult with a financial advisor before making any investment decisions.

### PR DESCRIPTION
**Pull request by 0xMakka**
## Description

Adds a disclaimer modal to Buy, Stake, Bonds & Wrap views. 

## Related Ticket

Resolves #1741

## Checklist

- [X] I have run `npm run build-all` without errors
- [X] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

**Review by jabby09 — CHANGES_REQUESTED** [review]
@0xMakka thanks for quick turnaround on this

Is it possible to shrink all this so the modal fits properly and I don't need to scroll on a typical macbook laptop screen?
Screenshot 2023-10-25 at 7 41 11 AM

**Comment by 0xMakka** [comment]
> @0xMakka thanks for quick turnaround on this
> 
> Is it possible to shrink all this so the modal fits properly and I don't need to scroll on a typical macbook laptop screen? Screenshot 2023-10-25 at 7 41 11 AM

@jabby09 I've reduced the text size of the content, removed extra whitespace between the title and content also. Can you see if this helps? Here it is on my 14-inch macbook screen

Screenshot 2023-10-25 at 11 59 19

**Review by jabby09 — CHANGES_REQUESTED** [review]
@0xMakka desktop is looking good (still checking all browsers)

Can you take another look at mobile?

On my phone I can find a way to have the modal as the focus but my swipe up gesture is grabbing the underlying page, so I can't get the modal to scroll down to the accept button. 

From what I can tell, the modal is sitting on top but I'm not sure it is enforcing focus; somehow if I tap around I can get the background screen to react to my gestures.

Hopefully that makes sense.

**Comment by 0xMakka** [comment]
> @0xMakka getting there...
> 
> the focus on mobile is fixed
> 
> however, now when I gesture up (to scroll the modal to the bottom) when I release my finger the modal bounces back to the top - so I can never click the accept button. It ends up hidden behind the Chrome footer controls.
> IMG_E1647BB47765-1
> 
> 
> 

Hey @jabby09, made some more fixes around mobile. Can you check did it fix the issues you are seeing?

**Review by jabby09 — APPROVED** [review]
Looks good!

**Review by Atmosfearful — APPROVED** [review]

**Comment by Atmosfearful** [comment]
nailed it thank you!

**Pull request merged**
