### PR TITLE
[receipts] 2279 update receipt designs

### LINKED ISSUE #2279: [retirement] Proposed receipt enhancement
See [discord thread here](https://discord.com/channels/1135827610434289727/1208006619397627954).

The solution team has made the following proposed suggestions to the retirement receipts (digital and pdf).

[Figma page for reference](https://www.figma.com/file/mgCvQP7CPtj5tpgfXxTTDC/Untitled?type=design&node-id=0-1&mode=design&t=P0RdLUFOroJqIHEo-0).

**Digital receipt**
- [x] Remove the link to polygonscan? (transaction id should remain)
- [x] Copy for "Official Certificate for On-Chain Carbon Retirement Provided by Carbonmark.com" changed to "Certificate for Carbon Retirement".
- [x] About Carbonmark section can be removed, i.e. "With over 20 million verified digital carbon credits from hundreds of projects, Carbonmark offers the largest selection of digital carbon credits worldwide. Buy, sell, and retire digital carbon from any project instantly with zero-commission trading. Get started today."

**PDF certificate**
- [x] Polygonscan link can be removed (transaction id should remain)
- [x] Copy for "Official Certificate for On-Chain Carbon Retirement Provided by Carbonmark.com" changed to "Certificate for Carbon Retirement".

**Learn more links**
- [x] Remove learn more links in project details

### Updated designs
[Digital receipt (see desktop and mobile)](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=384-6422&mode=design&t=NzpVz2nNjBJBypSq-4)
[PDF receipt](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=384-6606&mode=design&t=NzpVz2nNjBJBypSq-4)

### PR DESCRIPTION
**Pull request by sprrwhwk**
## Related Ticket

Closes #2279 
## How to Test
* For receipt with profile image visit `/retirements/0xE3d5afbBeF1214cE6B51937a2E0dE4cfc6Eb82E6/5`
* For receipt without profile image visit `/retirements/0x087a7afb6975a2837453be685eb6272576c0bc06/6`

### CODE REVIEW

**Comment by jabby09** [comment]
@sprrwhwk is this ready for QA?

**Comment by sprrwhwk** [comment]
> @sprrwhwk is this ready for QA?

it's in draft-mode because I need to do some code cleanup first

**Review by jabby09 — CHANGES_REQUESTED** [review]
@sprrwhwk MOSS PDF download missing project description and still has View on PolygonScan link

[retirement_11_0xea4d28f8218f44c84c8d7cbae5deac41acf66ced.pdf](https://github.com/KlimaDAO/klimadao/files/14377451/retirement_11_0xea4d28f8218f44c84c8d7cbae5deac41acf66ced.pdf)

Digital receipt looks okay https://carbonmark-git-2279-update-receipt-designs-klimadao.vercel.app/retirements/brice.klima/11

**Review by jabby09 — CHANGES_REQUESTED** [review]
@sprrwhwk a new requirement that was just given to me today.

- [ ] for both the digital and pdf receipt, can you remove the quotes "" around the RETIREMENT MESSAGE.

Screenshot 2024-02-22 at 1 44 40 PM

**Pull request closed without merging**
