### PR TITLE
update contact form url

### LINKED ISSUE #1119: [hubspot] Update contact form URL
The hubspot form we are using as a contact form has change to https://share-eu1.hsforms.com/1RWJWvyrHT1C_an4cZOHH3gfhhlr

The following item needs to be updated with the new link:
- [x] The Contact option in the footer nav

### PR DESCRIPTION
**Pull request by 0xMakka**
## Description

Update the contact form url in the footer nav.

## Related Ticket

Resolves #1119 

## Checklist

- [X] I have run `npm run build-all` without errors
- [X] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

**Review by Atmosfearful — APPROVED** [review]

**Review by Atmosfearful — CHANGES_REQUESTED** [review]
Ah since it's used in two places, would you mind dropping this in lib/constants in the urls object?

**Comment by Atmosfearful** [comment]
Actually I think this conflicts with https://github.com/KlimaDAO/klimadao/pull/1114/files, can you just update the URLS all in that PR?

**Comment by 0xMakka** [comment]
> Actually I think this conflicts with https://github.com/KlimaDAO/klimadao/pull/1114/files, can you just update the URLS all in that PR?

Hey, yep was thinking I had made an update to move it to the constants file. Yep, will just update the url's in 1114 and close this PR.

**Comment by 0xMakka** [comment]
> Actually I think this conflicts with https://github.com/KlimaDAO/klimadao/pull/1114/files, can you just update the URLS all in that PR?

Hey, yep was thinking I had made an update to move it to the constants file. Yep, will just update the url's in 1114 and close this PR.

**Pull request closed without merging**
