### PR TITLE
Prevent charts from redrawing when scrolling on mobile

### LINKED ISSUE #1759: [klima data] [mobile] element redraw after scrolling
All elements which draw graphs/charts/diagrams redraw their content after every scroll. Tested on Chromium-based browsers and Firefox, portrait and landscape mode.

Video below demonstrates the issue.

https://github.com/KlimaDAO/klimadao/assets/128430614/182fff0a-897c-434a-9c63-4eb4cbd5c579

### PR DESCRIPTION
**Pull request by biwano**
## Description

Prevent charts from redrawing when scrolling on mobile

## Related Ticket

Resolves #1759

- [x] I have run `npm run build-all` without errors
- [x] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

**Comment by 0xtapi** [comment]
Issue still there for me on three different browsers 🤔

**Comment by 0xemc** [comment]
> Issue still there for me on three different browsers 🤔

Looks like this didn't quite fix it @biwano can you take a second look plz?

**Comment by biwano** [comment]
> > Issue still there for me on three different browsers 🤔
> 
> Looks like this didn't quite fix it @biwano can you take a second look plz?

Sorry about that, this one tricked me. It should work now.

**Comment by 0xtapi** [comment]
> Sorry about that, this one tricked me. It should work now. @0xtapi

Looks great! Works on all browsers I tested. No more seizure during scrolling ✅

**Comment by biwano** [comment]
> > Sorry about that, this one tricked me. It should work now. @0xtapi
> 
> Looks great! Works on all browsers I tested. No more seizure during scrolling ✅

Can you approve the merge request so I can merge? Thanks.

**Review by 0xtapi — APPROVED** [review]

**Review by sprrwhwk — APPROVED** [review]

**Pull request merged**
