### PR TITLE
Retire: Add menu link

### PR DESCRIPTION
**Pull request by ladytrekker**
## Description

This is the last step of the "Retire" epic: Add the menu link for the Retire page

The former closed PRs with discussions to each section have been:
- https://github.com/KlimaDAO/klimadao/pull/1224
- https://github.com/KlimaDAO/klimadao/pull/1238
- https://github.com/KlimaDAO/klimadao/pull/1241
- https://github.com/KlimaDAO/klimadao/pull/1244

## Related Ticket

Resolves https://github.com/KlimaDAO/klimadao/issues/1248

Preview Link: https://carbonmark-git-lady-link-retire-klimadao.vercel.app/retire

## Checklist

- [x] I have run `npm run build-all` without errors
- [x] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

**Review by Atmosfearful — APPROVED** [review]

**Comment by jabby09** [comment]
@ShimonD-KlimaDAO this gives you access to the entire "Retire" page and all the sections.

Overall [design](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=627-5649&t=y3bv1pd97lLdokHn-4)

[Test link](https://carbonmark-git-lady-link-retire-klimadao.vercel.app/retire)

###Testing notes:
1. Leaderboard feature is not implemented for v1 of this page, you can ignore any of the leaderboard parts of the design for now.
2. Link CTAs in some of the sections are implemented right justified so do not match the design. professor has been informed.
3. VIEW ALL RETIREMENTS shows an expanded Activity page in the design which does yet exists. For v1, this should direct the user to the existing /retirements page.

**Review by jabby09 — CHANGES_REQUESTED** [review]
hi @ladytrekker 

A few changes:

- [x] Please change the featured projects to the following projects:
https://www.carbonmark.com/projects/VCS-674-2014
https://www.carbonmark.com/projects/VCS-292-2020
https://www.carbonmark.com/projects/VCS-981-2017

- [ ] from professor...align the cta link text to the baseline of the heading text (designs updated), for example:
image

**Comment by ShimonD-KlimaDAO** [comment]
Issues found:

1. "Klima green" found in connecting spinner.
image

2. Figma has "Project", whereas the implementation has "Projects".
image

3. "for beneficiary" should be bold, and the space under it is too large compared to the figma:
image
image

4. All links look bold in the figma but aren't in the preview link.

5. Alignment is off. Last letter of the link should be vertically aligned with the last project card.
image

6. Curated list of projects includes Mangrove project, which has a $0 price because it's not available to buy.

7. When I'm connected with a wallet that doesn't have assets to retire in its portfolio, the message mentioned "listable" assets, which doesn't make sense in this context. Should be something along the lines of "No assets to retire."
image

8. Under "Quick Retire" - The text "trusted vendors" sounds a bit vague. Also, if the only option is to retire from a pool, is a pool a "trusted vendor"?

9. The gold outline of the project cards is thicker in figma. Also, the outline in the preview link doesn't cover the corners completely - there's a small white gap.
image

10. Minor inconsistency - there are 4 cards in both sections. The top section displays the 4th card in the middle, whereas the bottom displays it on the left.
image

**Comment by jabby09** [comment]
> 7\. When I'm connected with a wallet that doesn't have assets to retire in its portfolio, the message mentioned "listable" assets, which doesn't make sense in this context. Should be something along the lines of "No assets to retire."

@ladytrekker @ShimonD-KlimaDAO For number 7 above, I had professor actually do a design for Portfolio empty state. Forgot to include in my other feedback.

[Design here](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=823-9478&mode=design&t=SSBIVrAIZIlGHytI-4) 

Screenshot 2023-07-05 at 7 58 09 PM

**Comment by 0xtapi** [comment]
Most of the issues are fixed, some remain:

1. Alignment of links with project cards still off.
align

2. Wording issue of "trusted vendors" still present. Implies that there is a distinction between vendors we trust and vendors we don't trust or at least cannot vouch for—not a good look. Maybe something like "Here’s a list of readily available, discounted carbon tokens to retire quickly and easily" would be better. 

3. In CM's branding guidelines, it says we shouldn't use italic text anywhere. But:
italic
Not sure if this is a big deal. Onyx or Professor input needed 🤷‍♂️

**Comment by jabby09** [comment]
> Most of the issues are fixed, some remain:

@0xtapi @ladytrekker let me follow up with professor on these and get back to you.

**Review by jabby09 — CHANGES_REQUESTED** [review]
hi @ladytrekker 

1. For empty state on Portfolio section, the updated designs I provided don't appear in the preview link although you checked it as being done. See this comment https://github.com/KlimaDAO/klimadao/pull/1274#issuecomment-1622645759

2. Strange spacing between project title and description introduced on these cards
Screenshot 2023-07-07 at 9 44 38 AM

**Comment by ladytrekker** [comment]
> Most of the issues are fixed, some remain:
> 
> 1. Alignment of links with project cards still off.
>    align

I moved the cards now too

> 2. Wording issue of "trusted vendors" still present. Implies that there is a distinction between vendors we trust and vendors we don't trust or at least cannot vouch for—not a good look. Maybe something like "Here’s a list of readily available, discounted carbon tokens to retire quickly and easily" would be better.

Also unsure how to properly describe this section his in english. Shimon wasn't sure above either.
I took your text now. 

> 3. In CM's branding guidelines, it says we shouldn't use italic text anywhere. But:
>    italic

See your [own Figma screenshot](https://user-images.githubusercontent.com/103535195/251300392-0f156aa5-27cf-41f2-aab1-cdb4ca78e80f.png) => _ITALIC_

**Comment by jabby09** [comment]
> Most of the issues are fixed, some remain:

@ladytrekker @0xtapi 

for #3, from professor

> italics has to be ok in the app, imo. we need a distinction between static text and the text that's there only for specific use cases & empty states.

for #1, from professor

> it's fine because varying screensizes will have varying numbers of cards in that row, so it will be nearly impossible to align perfectly anyway

for #2, I'm getting a copy review from Sy...stand by

**Comment by ladytrekker** [comment]
> hi @ladytrekker
> 
> 1. For empty state on Portfolio section, the updated designs I provided don't appear in the preview link although you checked it as being done. See this comment [Retire: Add menu link #1274 (comment)](https://github.com/KlimaDAO/klimadao/pull/1274#issuecomment-1622645759)

The empty state from your screenshot is the state when a registered carbonmark user has no assets.
Did you check this with this kind of user (registered but no assets)?

Sidenote: Right now I am having issues to register users at all with the carbonmark API. 

> 2. Strange spacing between project title and description introduced on these cards
> 
> Screenshot 2023-07-07 at 9 44 38 AM

As descried in this PR https://github.com/KlimaDAO/klimadao/pull/1238#issue-1774614087
=> "The project description height is fixed which doesn't work well with the super long project title of the second project as now the description is cut off differently"
I decided to align the descriptions at the top.

Before it was like this:
 
Bildschirmfoto 2023-07-07 um 17 08 32

So what is your preference?

**Comment by jabby09** [comment]
> The empty state from your screenshot is the state when a registered carbonmark user has no assets. Did you check this with this kind of user (registered but no assets)?
> 
> Sidenote: Right now I am having issues to register users at all with the carbonmark API. Created a ticket here: #1289

@ladytrekker no I only tested a social login user that did not have a Carbonmark profile. But like you said, there is an error at the moment creating a profile.

**Comment by jabby09** [comment]
> So what is your preference?

Aligned to the top, like in the Marketplace. I have another ticket #967 to address the bug where the description does not fill the remaining space in the card.

**Review by jabby09 — APPROVED** [review]
will merge and fix minor nitpicks and copy in a different PR

**Review by Atmosfearful — APPROVED** [review]

**Pull request merged**
