### PR TITLE
Emc/fix/1944-profile-portfolio-issues

### PR DESCRIPTION
**Pull request by 0xemc**
## Description

* Replace a `=== null` check that was failing because of `undefined`
* Pass the User object directly from getStaticProps rather than through SWRConfig

Resolves the following from #1944:
- [x] When I access another users public profile (for example https://www.carbonmark.com/users/offsetra) the initial screen view flashes the Listings - No active listings page before rendering properly

`JABBY CONFIRMS FIXED`

- [x] Recent portfolio page content changes that were merged as part of https://github.com/KlimaDAO/klimadao/issues/1063 not longer seem to be there anymore. Currently if you do not have a profile, the Portfolio page is completely blank.

`JABBY CONFIRMS FIXED`

- [x] A new login with no Profile created should still show the temp avatar and wallet and stats / activity components. The figma design for a seller that has logged in but not yet set up their profile is [here](https://www.figma.com/file/tnBViWV19Ln9jjFDekksY7/Profile?type=design&node-id=13-13294&mode=design&t=g8WQBIgLuA3J3cXB-4); assuming the Marketplace navigation item is still active; i.e. start from the marketplace, click login, go through the login modal, end up on this page.

`JABBY CONFIRMS FIXED`

### CODE REVIEW

**Review by jabby09 — COMMENTED** [review]
@0xemc which two issues does this PR fix?

**Comment by 0xemc** [comment]
> @0xemc which two issues does this PR fix?

@jabby09 I'll be adding them in the description as I go. If you'd like to confirm on the preview link that'd be good or wait until they're all finshed

**Comment by 0xemc** [comment]
@jabby if you're ok with these fixes we can close this PR and tackle the others after. 

I need to clarify the logged in user without an account requirement too btw

CC: @Atmosfearful

**Comment by jabby09** [comment]
> if you're ok with these fixes we can close this PR and tackle the others after.

@0xemc checking now

**Pull request merged**
