### PR TITLE
DRAFT: home page Wormhole change

### LINKED ISSUE #492: Changing the text and image on the KlimaDAO main website home page
On the https://www.klimadao.finance/ homepage, need to replace the black hole for carbon section with new content and a video.

This is the website section being changed:
Image

_### Proposed Content_

**KlimaDAO is DeFi that defies climate change** 

KlimaDAO is the center of a new green economy. Built on the energy efficient Polygon network, KlimaDAO uses a stack of technologies to reduce market fragmentation and accelerate the delivery of climate finance to sustainability projects globally.

[insert video: https://youtu.be/eRmmDh1ingU]

_### Design Changes Required_

On desktop and mobile, update the [figma design file](https://www.figma.com/file/ITpEVoi0pVYDRSLpFOaCiz/LANDINGPAGE) replacing the black hole gif with a video

### PR DESCRIPTION
**Pull request by biwano**
## Description

On Home page
- Replaced Wormhole text
- Removed parralax wormhole image
- Added KlimaDAO youtube video

## Related Ticket

Resolves #492

## Changes

| Before  | After  |
|image|image|

-->

## Checklist

- [X] Building the site with `npm run build-site` works without errors
- [X] Building the app with `npm run build-app` works without errors
- [X] I formatted JS and TS files with running `npm run format-all`

### CODE REVIEW

**Comment by biwano** [comment]
I used this to prepare the youtube code: http://youtubeembedcode.com/en/
With the following configuration:
image

**Review by Atmosfearful — CHANGES_REQUESTED** [review]
* [x] please check mobile views, they look messed up in my devtools preview
* [ ] make sure intermediary breakpoints look OK too 
* [ ] add that 1.6rem border radius on the outer container div as per designs (needs `overflow: hidden` to work)
* [ ] bottom padding should be same as top padding so the elements are horizontally centered in the white section

**Comment by biwano** [comment]
@jabby09 There is a comment in figma about the fonts. I am not sure if I am supposed to change them or not.

**Review by jabby09 — APPROVED** [review]
@biwano yes I saw that comment. If you using the same font and styling that already exists on the Klima website we should be good. I think what is best is get this into dev and a link I can share with our content lead for confirmation.

**Comment by biwano** [comment]
> @biwano yes I saw that comment. If you using the same font and styling that already exists on the Klima website we should be good. I think what is best is get this into dev and a link I can share with our content lead for confirmation.

Hi! You can check the changes in the Vercel deployment associated with this PR. The link is above.
image


@Atmosfearful Thanks for commiting the locales.

**Review by Atmosfearful — APPROVED** [review]

**Comment by jabby09** [comment]
@Atmosfearful @biwano will this auto deploy to Stage and Production?

This issue and PR is closed but the site is not update yet.

**Comment by biwano** [comment]
> @Atmosfearful @biwano will this auto deploy to Stage and Production?
> 
> This issue and PR is closed but the site is not updated yet.

It should. If I remember correctly, it is not immediate. There is an automatic deployment twice a week.

**Pull request merged**
