### PR TITLE
Api/new activity route

### PR DESCRIPTION
**Pull request by biwano**
## Description

- Adds activity routes to the API
- Prevents the API `/projects` route from fetching project's activities

## Related Ticket

Also related to #1893

## Notes For QA

Specific pages, components or journeys that might be affected:
- 

Relevant preview URLs:
- 

Other notes:
-

### CODE REVIEW

**Review by 0xemc — CHANGES_REQUESTED** [review]
I think the `carbonmark/.generated/` folder and the `package-lock.json` might have accidentally been included in this PR?

**Comment by biwano** [comment]
> I think the `carbonmark/.generated/` folder and the `package-lock.json` might have accidentally been included in this PR?

Arf sorry about that. Not my day.

**Comment by biwano** [comment]
> > I think the `carbonmark/.generated/` folder and the `package-lock.json` might have accidentally been included in this PR?
> 
> Arf sorry about that. Not my day.

@0xemc  Can you take a look again?

**Review by 0xemc — CHANGES_REQUESTED** [review]
Great PR 👍

The very last thing is to write some tests for the filters on the `/activity` route

`projectId` & `activityType`

**Review by 0xemc — APPROVED** [review]

**Pull request merged**
