### PR TITLE
fix: Resolve v2.0.0 and v2.0.3 api differences

### PR DESCRIPTION
**Pull request by 0xemc**
## Description

Because the API made an assumption of a one to one mapping of credits to projects (old technical debt)  only the first credit of any project was returning a project. This has been resolved by creating a new "Project" object per credit and adding it to the response.

Between v2.0.0 and v2.0.3 (the current version) the underlying subgraph has changed from 

https://api.thegraph.com/subgraphs/name/klimadao/polygon-bridged-carbon/

to

https://api.thegraph.com/subgraphs/name/klimadao/polygon-digital-carbon

The underlying data appears to be equivalent however the data structures are different with credits nested within projects. (@note we should really use the 'credits' graphql interface in the new subgraph)

### Number of projects returned:
v2.0.0.api.carbonmark.com ->  314
**this pr** ->  331

### Difference between api versions:
**Projects in V2.0.0 only**:  
[ 'VCS-903-2019' ]

**Projects in this PR only**:  [
  'VCS-1094-2009', 'VCS-1382-2015',
  'VCS-1566-2019', 'VCS-1671-2018',
  'VCS-1686-2017', 'VCS-1686-2019',
  'VCS-1715-2017', 'VCS-1762-2019',
  'VCS-1792-2020', 'VCS-1985-2019',
  'VCS-2307-2018', 'VCS-614-2010',
  'VCS-614-2011',  'VCS-614-2012',
  'VCS-614-2013',  'VCS-614-2014',
  'VCS-614-2015',  'VCS-614-2016'
]

There is a single project present in the old api that is not present in the new one 'VCS-903-2019' this is a result of the same Credit present across multiple Bridges (see: https://github.com/KlimaDAO/klimadao/issues/1994)

Additionally since this change some projects are now present that were not visible before.. I am not sure if they were hidden previously or if they are in error.

## Related Ticket

Closes 1987

## Notes For QA
We need to confirm that the newly visible projects are legitimate and not duplicates or contain some error.

### CODE REVIEW

**Review by Atmosfearful — CHANGES_REQUESTED** [review]
still only seeing 1 project here when it should be 2

https://carbonmark-api-git-emc-fix1987-project-mismatch-klimadao.vercel.app/projects?search=VCS-903

ideally we can get this fixed in the same pr

**Review by jabby09 — COMMENTED** [review]
@0xemc 

These projects are showing in both production and PR versions for CM. Perhaps when you did the comparison the api had updated in prod and only 153 projects were there.

'VCS-1094-2009', 'VCS-1382-2015',
'VCS-1566-2019', 'VCS-1671-2018',
'VCS-1686-2017', 'VCS-1686-2019',
'VCS-1715-2017', 'VCS-1762-2019',
'VCS-1792-2020', 'VCS-1985-2019',
'VCS-2307-2018', 'VCS-614-2010',

I did notice with a lot of these projects that the quantity is < 1 tonne. 

But also weird that the Quantity Available does not match Remaining Supply in Stats, see https://carbonmark-git-emc-fix1987-project-mismatch-klimadao.vercel.app/projects/VCS-1686-2017 as example 

Or maybe it never did? or is there a different source for this data?

The VCS-614 projects:
'VCS-614-2011', 'VCS-614-2012',
'VCS-614-2013', 'VCS-614-2014',
'VCS-614-2015', 'VCS-614-2016'

Are throwing a invalid category name error currently in production
Screenshot 2023-12-07 at 12 16 36 PM

**Comment by 0xemc** [comment]
> still only seeing 1 project here when it should be 2
> 
> https://carbonmark-api-git-emc-fix1987-project-mismatch-klimadao.vercel.app/projects?search=VCS-903
> 
> ideally we can get this fixed in the same pr

I am 95% sure this is related to this issue https://github.com/KlimaDAO/klimadao/issues/1994

I mentioned it earlier but essentially.

1. there are two assets for the VCS-903 project with a vintage of 2019
2. we create a key for each of these that is `VCS-903-2019`
3. the first is overwritten by the second in [ProjectMap](https://github.com/KlimaDAO/klimadao/blob/f84950806f5e0f740b8a8a1d16c85b0f4b7fc0b6/carbonmark-api/src/routes/projects/get.ts#L96)
4. And the second has a balance of 0 in all the pools

**Comment by 0xemc** [comment]
> VCS-1382-2015'

I think the prod version when you were testing might have been the accidental release that we reverted. If you check for those projects now they don't appear to be there:

https://www.carbonmark.com/projects?layout=grid&sort=recently-updated&search=VCS-1382

image

>Are throwing a invalid category name error currently in production

I have fixed this in this PR actually, it must have leaked in since v2.0.0 as well

https://github.com/KlimaDAO/klimadao/pull/1990/files#diff-aa8326678d7f8aaa525a4b374d8d66ee3e545d03d203206510dc47ffc839f196R59

**Review by jabby09 — COMMENTED** [review]
@0xemc 
this one https://www.carbonmark.com/projects?layout=grid&sort=recently-updated&search=VCS-1382 

shows Quantity=0 in the PR 

https://carbonmark-git-emc-fix1987-project-mismatch-klimadao.vercel.app/projects/VCS-1382-2015 

So it is likely being filtered out

**Comment by jabby09** [comment]
> I have fixed this in this PR actually, it must have leaked in since v2.0.0 as well

@0xemc why on the front end do we use a category label of `Other` when I can filter using `Industrial Processing`?

Screenshot 2023-12-07 at 3 45 49 PM

**Comment by 0xemc** [comment]
Screenshot 2023-12-08 at 12 00 19 pm

>But also weird that the Quantity Available does not match Remaining Supply in Stats, see https://carbonmark-git-emc-fix1987-project-mismatch-klimadao.vercel.app/projects/VCS-1686-2017 as example
>Or maybe it never did? or is there a different source for this data?

Yes strange.. investigating now

**Comment by 0xemc** [comment]
> Screenshot 2023-12-08 at 12 00 19 pm
> > But also weird that the Quantity Available does not match Remaining Supply in Stats, see https://carbonmark-git-emc-fix1987-project-mismatch-klimadao.vercel.app/projects/VCS-1686-2017 as example
> > Or maybe it never did? or is there a different source for this data?
> 
> Yes strange.. investigating now

@jabby09 this difference between the supply in stats and available in the listing seems to be unrelated to anything that's changed recently. Can we add it to another ticket so these changes can be delivered?

**Review by Atmosfearful — APPROVED** [review]
Good for now if you believe the missing projects should be tackled separately

**Pull request merged**
