### PR TITLE
Unify modal styling

### LINKED ISSUE #1220: [carbonmark] Align all buy/retire confirm modals
## Problem

Where we use Confirm modals during buy/purchase or retire transactions, there are slight variations on the modal UI elements, sizes, scroll etc.

## Examples

The Confirm Purchase modal (Buy from seller listing flow) has no GO BACK button, all the UI elements fit in the dimensions of the modal so no scroll required.
Screenshot 2023-06-16 at 10 56 25 AM

The Confirm Retirement modal (Retire from portfolio flow) has a GO BACK button, and I need to scroll to see all the UI elements.
Screenshot 2023-06-16 at 10 57 02 AM

When compared side-by-side, the modal width dimensions are not the same either.
Screenshot 2023-06-16 at 11 04 07 AM

## Ask

Ideally we can standardize the dimensions and UI elements to create a component so the modal experience is the same across the site. The one question would be how to handle situations where some modals have more text content requiring a need to scroll.

Beyond Confirm modals, are there other modals used in Carbonmark that can also be standardized into a component.

### PR DESCRIPTION
**Pull request by sprrwhwk**
## Description

This PR makes the `onGoBack` callback for modal dialogs mandatory. Additionally it replaces an occurence of `CustomizableModal` with the normal `Modal` for consistent styling

## Related Ticket

Resolves #1220 

## Checklist

- [x] I have run `npm run build-all` without errors
- [x] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

**Comment by 0xtapi** [comment]
Fix is working, but there seems to be a new bug:

1.) Both modals have the exact same width. Tested on Firefox and a bunch of Chromium browsers. ✅

2.) GO BACK button is there (and working). ✅

However, I could not test this on mobile with Metamask browser. When trying to connect, the Metamask option doesn't show. I can only access Coinbase, WalletConnect, and Circle Custody. ❌

Metamask option does show up on the same browser, same hardware, when I try it on the live version of carbonmark.com. I have not installed any extensions on this browser. I know we've had this issue several times in the past. Maybe related to those instances?

**Comment by jabby09** [comment]
> However, I could not test this on mobile with Metamask browser. When trying to connect, the Metamask option doesn't show. I can only access Coinbase, WalletConnect, and Circle Custody.

@Atmosfearful @ShimonD-KlimaDAO I don't have Metamask on mobile so I can't try and replicate this. Any thoughts?

**Comment by jabby09** [comment]
> @Atmosfearful @ShimonD-KlimaDAO I don't have Metamask on mobile so I can't try and replicate this. Any thoughts?

@Atmosfearful @ShimonD-KlimaDAO bump

**Comment by Atmosfearful** [comment]
Sorry for the delay, this one should be good to go if you can rebase/merge for me @sprrwhwk , the bug tapioka is reporting will be investigated in another ticket.

**Review by Atmosfearful — APPROVED** [review]

**Review by jabby09 — APPROVED** [review]

**Comment by jabby09** [comment]
> However, I could not test this on mobile with Metamask browser. When trying to connect, the Metamask option doesn't show. I can only access Coinbase, WalletConnect, and Circle Custody. ❌

@0xtapi as per above, we are going to merge this one in production and have you check again. If this is still an issue than we can create a new ticket to investigage.

**Pull request merged**
