### PR TITLE
0xMakka/1089 build retirement receipt page based on new designs

### LINKED ISSUE #1089: [retirement] Retirement receipt page based on new designs
This workstream is for the dev work required to build the new retirement receipt pages for Carbonmark.

[New designs here.](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=0-1&t=GsMARHHiNJnsw8V8-0)

### Notes
- [x] This workstream is focused solely on the retirement receipt page - the PDF version is covered in #1062 
- [x] Note design differences for [desktop](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=384-6420&t=GsMARHHiNJnsw8V8-4) and [mobile](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=384-6515&t=GsMARHHiNJnsw8V8-4)
- [x] URL structure will be `/retirements/[beneficiary_address]/[retirement_index]` ("single retirement page"; same pattern as in KlimaDAO)
- [x] For the `/retirements/[beneficiary_address]` ("retirements list") page, we will use what is currently deployed in staging, for example https://staging.carbonmark.com/retirements/brice.klima
- [x] For Project Details section, ignore the project photo, we will launch with the default project cover images based on project category
- [x] VIEW CARBONMARK PROFILE link CTA takes user to `https://www.carbonmark.com/users/login` or `https://www.carbonmark.com/users/[user]` if logged in
- [x] CREATE YOUR OWN RETIREMENT link CTA takes user to https://www.carbonmark.com/projects
- [x] LEARN MORE link CTA takes user to the project details page in Carbonmark
- [x] Get started today link CTA in the About Carbonmark section takes the user to https://www.carbonmark.com/projects
- [x] Beneficiary section - logo comes from the profile image
- [x] DOWNLOAD PDF hands off the PDF creation code (#1062)
- [x] Social share icons inherit behaviour as per already completed in the staging environment; for example, see https://staging.carbonmark.com/retirements/brice.klima/11 
Screenshot 2023-05-10 at 1 23 05 PM

- [x] Note the [designs changes](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=384-6853&t=GsMARHHiNJnsw8V8-4) that happen is no beneficiary information and/or retirement message is provided

### PR DESCRIPTION
**Pull request by 0xMakka**
## Description

Left to complete:

- [x] View Carbonmark Profile links
- [x] Create your own retirement link on desktop
- [x] Provided by Carbonmark.com link
- [x] Get started today link
- [x] Icon on Download PDF button

## Related Ticket

Resolves #1089

## Changes

screencapture-localhost-3002-retirements-0xa83148b098038f366534253704ae4ff3cf931b94-7-2023-05-17-21_37_19

screencapture-localhost-3002-retirements-0xa83148b098038f366534253704ae4ff3cf931b94-7-2023-05-17-21_37_42

## Checklist

- [x] I have run `npm run build-all` without errors
- [x] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

**Comment by jabby09** [comment]
@0xMakka I made a mistake on this requirement now that I see it in implementation:

> VIEW CARBONMARK PROFILE link CTA takes user to https://www.carbonmark.com/users/login or https://www.carbonmark.com/users/[user] if logged in

Please change so VIEW CARBONMARK PROFILE link CTA takes user to https://www.carbonmark.com/users/[user] always.

**Review by Atmosfearful — CHANGES_REQUESTED** [review]
One thing we forgot to mention in the requirements is how to handle MCO2 which does not have the "project selection" / pool redemption functionality that Toucan and C3 pools have.

Here is an example mco2 retirement:
https://carbonmark-git-makka-1089-new-retirement-receipt-page-klimadao.vercel.app/retirements/brice.klima/11

Change the URL to production and you can see how we handled it before (with a link to mco2 website)

**Comment by jabby09** [comment]
hey @0xMakka if you can address the change requested from atmos then I can re-test from UI perspective. thanks!

**Comment by 0xMakka** [comment]
> hey @0xMakka if you can address the change requested from atmos then I can re-test from UI perspective. thanks!

Hey @jabby09 the changes requested by atmos for the MCO2 links are in there now so think it should be good to retest. 👍

**Review by jabby09 — CHANGES_REQUESTED** [review]
hey @0xMakka 

Does not look like the default project image on the receipt is being updated to match the category so that will need to change. They all seem to be defaulting to the default image for category other.

Example, this is a renewable energy project but showing default image for category = other
https://carbonmark-git-makka-1089-new-retirement-receipt-page-klimadao.vercel.app/retirements/brice.klima/12

**Review by jabby09 — CHANGES_REQUESTED** [review]
hey @0xMakka 

For the twitter social share, can we please change #offset to #retirement

Screenshot 2023-05-24 at 2 28 42 PM

**Review by jabby09 — DISMISSED** [review]
hey @0xMakka 

Profile image changes:

If no image, then we should just hide it altogether and align all the text to the left
Screenshot 2023-05-24 at 3 05 17 PM

If there is an image, it should fill the available space with no white halo surrounding the image
Screenshot 2023-05-24 at 3 04 09 PM

**Comment by ShimonD-KlimaDAO** [comment]
1. "MUTABLE" should be "IMMUTABLE". This is also an error in the Figma design.
image

2. "Carbonmark.com" has a [broken link](https://carbonmark-git-makka-1089-new-retirement-receipt-page-klimadao.vercel.app/retirements/shimond.klima/carbonmark-hucxfcdnx-klimadao.vercel.app).
image

3. I think "ASSET RETIRED" is a bit inaccurate here. We are not retiring BCT, but we are redeeming a tco2 from BCT and then retiring the tco2. 
image

4. MCO2 "Project Name" is just "MCO2", which looks too bare. I think we should add a brief explanation as a "Project Description", and perhaps remove "Project Name" instead.
Something along the lines of "To learn more about the projects behind the MCO2 token, please visit ..."
image

5. The LinkedIn share button doesn't work for me.

6. When the user doesn't have a CM profile ([example](https://carbonmark-git-makka-1089-new-retirement-receipt-page-klimadao.vercel.app/retirements/0x2b1d879b5e102e60166202de79537b48e2f18a42/1)), the button "VIEW CARBONMARK PROFILE" points to "/users/undefined", which is a [broken link](https://carbonmark-git-makka-1089-new-retirement-receipt-page-klimadao.vercel.app/users/undefined).
image

**Comment by 0xMakka** [comment]
> 6\. example

Thanks @ShimonD-KlimaDAO for the feedback :)

1. This should now be updated.
2. I've Updated to always point to carbonmark.com and not the url based on the environment.
3. Should this then be changed to something like "Asset Redeemed"? @jabby09 any thoughts?
4. Yeah, I agree with this - can update this text to whatever the recommendation is from you guys. 👍 
5. Linkedin share button works for me, are you seeing an error message or something? (See attached screenshot)
6. What is the recommendation here, should we be hiding the "View carbonmark profile" link if the beneficiary doesn't have a carbonmark profile or hiding the full beneficiary card information. I know in the designs it says if a beneficiary/beneficiary address doesn't exist to hide the card - but maybe this falls under that requirement also? @jabby09 

linkedin

**Comment by jabby09** [comment]
> Thanks @ShimonD-KlimaDAO for the feedback :)
> 
> 1. This should now be updated.
> 2. I've Updated to always point to carbonmark.com and not the url based on the environment.
> 3. Should this then be changed to something like "Asset Redeemed"? @jabby09 any thoughts?
> 4. Yeah, I agree with this - can update this text to whatever the recommendation is from you guys. 👍
> 5. Linkedin share button works for me, are you seeing an error message or something? (See attached screenshot)
> 6. What is the recommendation here, should we be hiding the "View carbonmark profile" link if the beneficiary doesn't have a carbonmark profile or hiding the full beneficiary card information. I know in the designs it says if a beneficiary/beneficiary address doesn't exist to hide the card - but maybe this falls under that requirement also? @jabby09
> 
> linkedin

thanks @ShimonD-KlimaDAO and @0xMakka I'm working on getting answers for 3, 4, and 6

LinkedIn also works for me

**Comment by Atmosfearful** [comment]
A note on 3 "asset retired": Just beware that it's also possible to retire an asset you own directly, in this case this field should be empty (hidden?). If you need me to find an example of a retirement that didn't come from a pool let me know and I'll find one for you. I personally would be OK with removing this field altogether.

**Review by Atmosfearful — APPROVED** [review]
Code looks good, I only see 1 change worth mentioning. We can do it in a follow-up PR.
I'm going to run format-all on staging in a separate PR and merge it first, to remove all the unrelated formatting changes that snuck in this PR.

**Comment by 0xMakka** [comment]
> Code looks good, I only see 1 change worth mentioning. We can do it in a follow-up PR. I'm going to run format-all on staging in a separate PR and merge it first, to remove all the unrelated formatting changes that snuck in this PR.

@Atmosfearful thanks for the review - yeah I realised this after I ran format-all on the project I got all the carbonmark-api changes because it wasn't formatted on staging.

> A note on 3 "asset retired": Just beware that it's also possible to retire an asset you own directly, in this case this field should be empty (hidden?). If you need me to find an example of a retirement that didn't come from a pool let me know and I'll find one for you. I personally would be OK with removing this field altogether.

Yeah if you had an example that would be great so I can actually cater for this case. I'm happy to remove this field if that's what you guys agree on.

> There is no need to lazy load this anymore since we aren't loading the PDF library anymore. Just render the button directly

Yeah good shout, will address this as part of this PR as I'm waiting on answers from jabby on 3, 4, and 6 so will most likely have to make some changes here regardless. 👍

**Comment by Atmosfearful** [comment]
@0xMakka It looks like it correctly says "TCO2" already 🔥
https://carbonmark-git-makka-1089-new-retirement-receipt-page-klimadao.vercel.app/retirements/atmosfearful.klima/6

**Comment by Atmosfearful** [comment]
As for 6 - "view carbonmark profile" button - the carbonmark application is able to resolve any 0x address to a skeleton profile page, for example here is markcuban.klima - https://carbonmark-git-makka-1089-new-retirement-receipt-page-klimadao.vercel.app/users/0x293ed38530005620e4b28600f196a97e1125daac

So as a simple fix I will sneak a commit in this PR that always passes the beneficiary address to the URL, that way we can always resolve a link.

But I think we should revisit this based on discussions we had in our product sync meeting today-- if profiles are only for sellers, it doesn't make much sense to show a seller profile picture and profile on a retirement page...

**Comment by Atmosfearful** [comment]
I've also added a commit to address this @jabby09 https://github.com/KlimaDAO/klimadao/pull/1140#pullrequestreview-1442491203

**Pull request merged**
