### PR TITLE
Basic Lucky Orange tracking

### LINKED ISSUE #1086: [analytics] Add event tracking for LuckyOrange
# Carbonmark LuckyOrange Events

## Docs 
https://developers.luckyorange.com/libraries/browser
If using browser implementation use the ES5 syntax when calling ready() since we're using GTM

## Events to track

Login
`LO.events.track('Login')`

UserID
`LO.visitor.identify('wallet', { user: 'username', name: 'Display Name' })`

Purchase: Buy Clicked
`LO.events.track('Purchase: Buy Clicked')`

Purchase: Continue Clicked
`LO.events.track('Purchase: Continue Clicked')`

Purchase: Approve Clicked
`LO.events.track('Purchase: Approve Clicked')`

Purchase: Submit Clicked
`LO.events.track('Purchase: Submit Clicked')`

Purchase: Purchase Completed
`LO.events.track('Purchase: Purchase Completed')`

Purchase: Purchase Modal Closed
`LO.events.track('Purchase: Purchase Modal Closed')`

Retire: Retire Button Clicked
`LO.events.track('Retire: Retire Button Clicked')`

Listing: Sell Clicked
`LO.events.track('Listing: Sell Clicked')`

Listing: Approve Clicked
`LO.events.track('Listing: Approve Clicked')`

Listing: Listing Created
`LO.events.track('Listing: Listing Created')`

Listing: Edit Clicked
`LO.events.track('Listing: Edit Clicked')`

Listing: Updated
`LO.events.track('Listing: Updated')`

Listing: Deleted
`LO.events.track('Listing: Deleted')`

### PR DESCRIPTION
**Pull request by biwano**
- [ ] ## Description

LuckyOrange Events 

- [x] Login
LO.events.track('Login')
Note: Tracks only identified Carbonmark users

- [x] UserID
LO.visitor.identify('wallet', { user: 'username', name: 'Display Name' })
Note: Tracks only identified Carbonmark  users

- [x] Purchase: Buy Clicked
LO.events.track('Purchase: Buy Clicked')

- [x] Purchase: Continue Clicked
LO.events.track('Purchase: Continue Clicked')
Note: Triggers only if the form is valid.

- [ ] Purchase: Approve Clicked
LO.events.track('Purchase: Approve Clicked')

- [ ] Purchase: Submit Clicked
LO.events.track('Purchase: Submit Clicked')

- [ ] Purchase: Purchase Completed
LO.events.track('Purchase: Purchase Completed')

- [ ] Purchase: Purchase Modal Closed
LO.events.track('Purchase: Purchase Modal Closed')

- [ ] Retire: Retire Button Clicked
LO.events.track('Retire: Retire Button Clicked')

- [ ] Listing: Sell Clicked
LO.events.track('Listing: Sell Clicked')

- [ ] Listing: Approve Clicked
LO.events.track('Listing: Approve Clicked')

- [ ] Listing: Listing Created
LO.events.track('Listing: Listing Created')

- [ ] Listing: Edit Clicked
LO.events.track('Listing: Edit Clicked')

- [ ] Listing: Updated
LO.events.track('Listing: Updated')

- [ ] Listing: Deleted
LO.events.track('Listing: Deleted')

## Related Ticket

Resolves #1086 

## Changes

NA

## Checklist

- [ ] I have run `npm run build-all` without errors
- [ ] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

**Comment by biwano** [comment]
@jabby @Atmosfearful I added base code for LuckyOrange custom tracking.
Calls to LuckyOrange library seem to be alright but no requests are make to the Luckyorange server. Plus their tag is included by GTM so I am a bit blind.
Question is: is luckyOrange configured so no calls are made when in developer mode?

**Comment by jabby09** [comment]
> @jabby @Atmosfearful I added base code for LuckyOrange custom tracking. Calls to LuckyOrange library seem to be alright but no requests are make to the Luckyorange server. Plus their tag is included by GTM so I am a bit blind. Question is: is luckyOrange configured so no calls are made when in developer mode?

@sy-zygy do you know the answer to this question?

**Comment by jabby** [comment]
hello @biwano I unsuscribed as I think I'm not the right person here. 😄

**Comment by jabby09** [comment]
@biwano I'm jabby09

Can we release 1 or 2 of the events in production and then we can test that the events are firing?

**Comment by biwano** [comment]
> @biwano I'm jabby09
> 
> Can we release 1 or 2 of the events in production and then we can test that the events are firing?

Sure. This PR should be now OK for this purpose.

**Review by Atmosfearful — APPROVED** [review]
Looks good to me! I was a bit concerned that having both an onClick and an href on our buttonprimary might cause problems, but I think the component can handle it. Let's get it on prod and see how the events turn out! Thanks!

**Pull request merged**
