### PR TITLE
0xMakka - replace description with short/long_description

### LINKED ISSUE #1149: [projects] Update descriptions from enriched content
Enriched and enhanced project descriptions have been created using a custom GPT script by Sy Zygy, uploaded to Sanity via script.

Need to update the API to include project long and short description from the new Sanity type and then update the frontend to reflect that new data.

Project Content here: https://carbon-projects.sanity.studio/desk/projectContent
Has a `Short Description` and `Long Description` field

Long description will be used on the project details pages.
Short description will be used on the project cards in the marketplace and meta description tag.

### PR DESCRIPTION
**Pull request by 0xMakka**
## Description

Replace the description field with short description on /projects view and long description on /projects/{projectId} views.

## Related Ticket

Resolves #1149 

## Checklist

- [x] I have run `npm run build-all` without errors
- [x] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

**Review by jabby09 — DISMISSED** [review]
looks like the new improved enriched project descriptions is breaking our design, for example... https://carbonmark-git-makka-1149-update-descriptions-f-954575-klimadao.vercel.app/projects/VCS-191-2008

Raising this with @sy-zygy and @theprofessora 

For now do not merge this PR.

**Comment by 0xMakka** [comment]
> looks like the new improved enriched project descriptions is breaking our design, for example... https://carbonmark-git-makka-1149-update-descriptions-f-954575-klimadao.vercel.app/projects/VCS-191-2008
> 
> Raising this with @sy-zygy and @theprofessora
> 
> For now do not merge this PR.

@jabby09 I can add in a maximum height on the description area so it never goes larger than the height of the map and show a scroll bar when the content is larger but probably best to let @theprofessora to propose a solution.

See image below:
Screenshot 2023-06-07 at 15 19 56

**Comment by theprofessora** [comment]
I don't like having multiple scroll bars on a single page. I think we should do a selective disclosure model, shown here:

**Comment by jabby09** [comment]
@0xMakka the consensus is to move forward with a Read More / Read Less implementation, see professor design above.

[Update design here](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/%2Fprojects?type=design&node-id=753-27856&t=oybITAVtcwF8za0Q-4)

**Comment by 0xMakka** [comment]
> I don't like having multiple scroll bars on a single page. I think we should do a selective disclosure model, shown here: image

> @0xMakka the consensus is to move forward with a Read More / Read Less implementation, see professor design above.

@theprofessora / @jabby Agreed multiple scroll bars probably isn't a great approach. Great, I like the idea of the Read More/Read Less implementation - will implement this later :)

**Pull request merged**
