### PR TITLE
[provenance] 2281 Fix provenance page bugs

### LINKED ISSUE #2281: [provenance] Change "Bridge" terminology to "Transfer"
[See discord thread](https://discord.com/channels/1135827610434289727/1208035240291864606)

Overall, let's start using 'transfer' as the term to describe the movement of credits to/from registry accounts to our platform.

- [x] Request to change `Bridge` label on provenance pages to `Transfer`

image

### PR DESCRIPTION
**Pull request by sprrwhwk**
## Description
This PR replaces the string "Bridge" with "Transfer" on the provenance receipt page.

## Related Ticket

Closes #2281 
Also related to <issue-number>

## How to Test
Visit https://carbonmark-git-2281-get-rid-of-bridge-term-klimadao.vercel.app/retirements/0x087a7afb6975a2837453be685eb6272576c0bc06/6/provenance

### CODE REVIEW

**Review by jabby09 — CHANGES_REQUESTED** [review]
@sprrwhwk I think you missed the full requirements of this issue, I tagged you in this comment https://github.com/KlimaDAO/klimadao/issues/2281#issuecomment-1952618695

[Updated designs](https://www.figma.com/file/7N5csmr1NPeKefGh5MuGeh/Carbon-Provenance?type=design&node-id=1-90&mode=design&t=oVdiE8Dh1lXLoZlw-4)

A few changes were necessary here:

1. changed "Bridge" to "Transfer"
2. changed "Transfer" to "Send"
3. Added info icon w/ tooltip explaining that a Send is when an "Asset moved from one account to another, either via sale or inter-account transfer."
4. Changed "view/hide XX transfers" to "view/hide XX transactions"

image

**Comment by sprrwhwk** [comment]
> @sprrwhwk I think you missed the full requirements of this issue, I tagged you in this comment [#2281 (comment)](https://github.com/KlimaDAO/klimadao/issues/2281#issuecomment-1952618695)
> 
> [Updated designs](https://www.figma.com/file/7N5csmr1NPeKefGh5MuGeh/Carbon-Provenance?type=design&node-id=1-90&mode=design&t=oVdiE8Dh1lXLoZlw-4)
> 
> A few changes were necessary here:
> 
>     1. changed "Bridge" to "Transfer"
> 
>     2. changed "Transfer" to "Send"
> 
>     3. Added info icon w/ tooltip explaining that a Send is when an "Asset moved from one account to another, either via sale or inter-account transfer."
> 
>     4. Changed "view/hide XX transfers" to "view/hide XX transactions"
> 
> 
> image

I had missed that indeed @jabby09. I worked with the original issue comment at first.

I've addressed all of your requirements now. Can you have another look?

**Review by jabby09 — CHANGES_REQUESTED** [review]
@sprrwhwk 

Issue here with number of transactions:
Screenshot 2024-02-21 at 9 40 59 AM

Also, the icons don't appear to be circles, stretched vertically

Screenshot 2024-02-21 at 9 42 02 AM

**Comment by jabby09** [comment]
> Can you try removing any locale from the url (e.g. `carbonmark.com/de/…` and reloading the page? The `{numberOfTransfers}` is caused by our translation tooling.

@sprrwhwk hmmm....no locale in this url and still seeing the issue
https://carbonmark-git-2281-get-rid-of-bridge-term-klimadao.vercel.app/retirements/0x087a7afb6975a2837453be685eb6272576c0bc06/6/provenance

**Review by jabby09 — APPROVED** [review]

**Pull request closed without merging**
