### PR TITLE
/users/login to /login

### PR DESCRIPTION
**Pull request by 0xemc**
## Description

* correct folder structure for [walletOrHandle] and [wallet] user endpoints
* move /login out of /users
* removes manual `/user` api functions and replaces with sdk functions

### CODE REVIEW

**Review by biwano — APPROVED** [review]
These routes are not used in the UI yet. Right?

**Comment by 0xemc** [comment]
> These routes are not used in the UI yet. Right?

They are actually yea, when authenticating in Carbonmark

**Comment by 0xemc** [comment]
> > > These routes are not used in the UI yet. Right?
> > 
> > 
> > They are actually yea, when authenticating in Carbonmark
> 
> Sorry for my noobness but can you explain how it works? When I reviewed the PR, I put some console logs in those API routes, logged in with metamask and tor and I could not see the browser requests nor the API logs.

No noobness at all, I realised that we had manual functions calling the api end points directly (thereby skipping the api sdk).

If you pull the latest changes you should see your logs firing (assuming everything builds this run)

**Review by 0xMakka — APPROVED** [review]

**Comment by 0xemc** [comment]
@0xtapi when you get a chance can you QA the auth aspects of carbonmark please? login, sign up, create account etc

**Comment by 0xtapi** [comment]
Tested, errors found:

- Trying to create a profile returns "Something went wrong. Please try again. TypeError: Failed to fetch"

Console screenshot:

Screenshot 2023-12-04 150200


Logging in and out and switching accounts works.

**Comment by 0xemc** [comment]
> Tested, errors found:
> 
> * Trying to create a profile returns "Something went wrong. Please try again. TypeError: Failed to fetch"
> 
> Console screenshot:
> 
> Screenshot 2023-12-04 150200
> Logging in and out and switching accounts works.

@0xtapi can you re-confirm in here that the create issue is fixed plz?

**Pull request merged**
