### PR TITLE
implement segmented button layouts

### LINKED ISSUE #1573: [carbon dashboard] fix widget css on tabbed pages
This looks like this now: 

- Off vs On-chain carbon
image

- Token details page
image

### PR DESCRIPTION
**Pull request by sprrwhwk**
## Description
This PR implements the layout for the segmented buttons.

Resolves #1573

### CODE REVIEW

**Review by biwano — CHANGES_REQUESTED** [review]
It looks good for the retirement trends page but the off vs on page does not show on your version. Maybe you need to merge staging.

**Comment by sprrwhwk** [comment]
> It looks good for the retirement trends page but the off vs on page does not show on your version. Maybe you need to merge staging.

I don't understand. This PR is up to date with staging. 😕

**Comment by sprrwhwk** [comment]
I believe you were referring to #1569 not being merged yet. We can rebase this branch after that PR is merged to staging.

**Comment by biwano** [comment]
> I believe you were referring to #1569 not being merged yet. We can rebase this branch after that PR is merged to staging.

Exactly! My bad. I tought it was already on staging because I branched from that. It is merged now.

**Review by biwano — APPROVED** [review]
Good to go !

**Pull request merged**
