### PR TITLE
2062 converted objects to interpolated strings

### PR DESCRIPTION
**Pull request by sidneyarida**
## Description

1st part of #2062 

Converted translation objects to interpolated strings

Other notes:
-

Translation keys are changed and will need to re-translate.

From the the [migration guide](https://lingui.dev/releases/migration-4)  (screenshot below) they suggest to add this comment **#. js-lingui-explicit-id** ontop of the key, but from I understood from the project the keys are handled with translations.io and the language files are overwritten. 
So I think it's not doable and may need to re-insert the translations
How do we want to manage it?

Screenshot 2024-01-17 at 15 29 40

### CODE REVIEW

**Review by 0xemc — APPROVED** [review]

**Comment by 0xemc** [comment]
@biwano I'm not sure I understand if this will impact us or not

>From the the [migration guide](https://lingui.dev/releases/migration-4) (screenshot below) they suggest to add this comment #. js-lingui-explicit-id ontop of the key, but from I understood from the project the keys are handled with translations.io and the language files are overwritten.
So I think it's not doable and may need to re-insert the translations
How do we want to manage it?

Any ideas?

**Comment by biwano** [comment]
> @biwano I'm not sure I understand if this will impact us or not
> 
> > From the the [migration guide](https://lingui.dev/releases/migration-4) (screenshot below) they suggest to add this comment #. js-lingui-explicit-id ontop of the key, but from I understood from the project the keys are handled with translations.io and the language files are overwritten.
> > So I think it's not doable and may need to re-insert the translations
> > How do we want to manage it?
> 
> Any ideas?

Hi 

If memory serves right, the PO files are updated via the `update_translations.yml` with `npm run extract-strings`. That command
- extracts strings into PO files 
- gets translations from 
- sends new keys to translation.io
The new keys would have no translations. So everything would need to be translated again.

There is maybe one option to not have to retranslate everything: 
- Create a new project
- Initialize the project translations with this https://translation.io/docs/create-library#initialization. It would require a script to convert existing translations into segments
- Switch carbonmark translation.io configuration to use the new project

**Comment by 0xemc** [comment]
This PR keeps getting kicked further down the road and I think we should just bite the bullet.

@brunoilponseisae @Atmosfearful If you both agree I think we should merge this and then deal with the consequences (updating translations, shifting to machine translations etc).

**Comment by 0xemc** [comment]
@sidneyarida can you resolve the conflicts please 🙏

**Review by Atmosfearful — APPROVED** [review]
LFG let's get this in before we switch to the private repo. We can suffer the broken translations. I'll let @0xtapi know we should brace for impact

**Pull request merged**
