### PR TITLE
Fix Coinbase and Torus bugs, update web3 dependencies

### LINKED ISSUE #659: Coinbase Wallet menu item is broken
image

### PR DESCRIPTION
**Pull request by Atmosfearful**
## Description

- migrate to the new Coinbase wallet repo instead of walletlink
- hacky fix for a bug related to coinbase default export being broken since we don't use Babel
- upgrade ethers, torus, coinbase, walletconnect
- force logout by explicitly calling `logout()` on torus accounts before clearing the cache
- disable caching for web3modal

In addition to fixing coinbase #659 this should _hopefully_ fix 3 rare bugs that don't have tickets:
1. `polygon` network modal was incorrectly shown for torus users sometimes
2. infinite re-connect loop would sometimes happen with torus
3. if you have two torus accounts, it wasn't possible to disconnect and log into your other account, because it would always use your previously cached login.

## Related Ticket
I confirmed that coinbase is working again:
Resolves #659 

## Checklist

- [x] Building the site with `npm run build-site` works without errors
- [x] Building the app with `npm run build-app` works without errors
- [x] I formatted JS and TS files with running `npm run format-all`

### CODE REVIEW

**Comment by jabby09** [comment]
@Atmosfearful testing here: https://klimadao-app-git-upgrade-deps-klimadao.vercel.app/#/stake

- Coinbase option opened for me in chrome
- On chrome, the torus connect worked. I was able to connect and disconnect without the polygon error. I was able to connect using various social logins, disconnect and login in again using something different
- I still have an error/issue when in incognito mode (maybe this is expected). When I click on the Email or Social option nothing happens. Screenshot of console below
![Uploading Screen Shot 2022-09-14 at 9.36.58 AM.png…]

**Comment by jabby09** [comment]
@Atmosfearful I tested here: https://klimadao-app-git-upgrade-deps-klimadao.vercel.app/#/stake

- on chrome i was able to open the coinbase option no problem
- on chrome is was able to connect / disconnect using torus social login with no issues. i could connect using different social options, disconnect, and then connect again using a different option
- i'm still getting an issue when in incognito mode. when i click on Email or Social option nothing happens. screenshot of console below

Screen Shot 2022-09-14 at 9 40 02 AM

**Comment by Atmosfearful** [comment]
> @Atmosfearful I tested here: https://klimadao-app-git-upgrade-deps-klimadao.vercel.app/#/stake
> 
> * on chrome i was able to open the coinbase option no problem
> * on chrome is was able to connect / disconnect using torus social login with no issues. i could connect using different social options, disconnect, and then connect again using a different option
> * i'm still getting an issue when in incognito mode. when i click on Email or Social option nothing happens. screenshot of console below
> 
> Screen Shot 2022-09-14 at 9 40 02 AM

@jabby09 Aha so for the last item there, I lost a lot of time to this, and found a solution. It's actually silly.
**Chrome seems to be blocking all cookies in incognito now (is this new??)**
You will see an eyeball appear on the top right in chrome, which you can click and "enable cookies". If you do that then torus seems to work.

The only solution I can think of is to see if the browser gives us an API to detect when cookies are disabled like this, and present a modal educating them how to fix it. But this is only relevant when the torus modal is open... and at the moment the torus modal is fully managed by the torus library, I have no control over it 😭 

Let's make a ticket and see if any one else reports this issue in the wild. Hopefully it only applies to incognito. IF that is the only issue then I say we can merge this now!

**Comment by jabby09** [comment]
> > * i'm still getting an issue when in incognito mode. when i click on Email or Social option nothing happens. screenshot of console below
> 
> @jabby09 Aha so regarding this incognito bug, I lost a lot of time to this yesterday, and found a solution that I forgot to mention in the PR description. It's actually silly. **Chrome seems to be blocking all cookies in incognito now (is this new??)** You will see an eyeball appear on the top right in chrome, which you can click and "enable cookies". If you do that then torus seems to work.
> 
> The only solution I can think of is to see if the browser gives us an API to detect when cookies are disabled like this, and present a modal educating them how to fix it. But this is only relevant when the torus modal is open... and at the moment the torus modal is fully managed by the torus library, I have no control over it 😭
> 
> Let's make a ticket and see if any one else reports this issue in the wild. Hopefully it only applies to incognito. IF that is the only issue then I say we can merge this now!

@Atmosfearful

**Comment by jabby09** [comment]
zfsdfds

**Comment by jabby09** [comment]
> > * i'm still getting an issue when in incognito mode. when i click on Email or Social option nothing happens. screenshot of console below
> 
> @jabby09 Aha so regarding this incognito bug, I lost a lot of time to this yesterday, and found a solution that I forgot to mention in the PR description. It's actually silly. **Chrome seems to be blocking all cookies in incognito now (is this new??)** You will see an eyeball appear on the top right in chrome, which you can click and "enable cookies". If you do that then torus seems to work.
> 
> The only solution I can think of is to see if the browser gives us an API to detect when cookies are disabled like this, and present a modal educating them how to fix it. But this is only relevant when the torus modal is open... and at the moment the torus modal is fully managed by the torus library, I have no control over it 😭
> 
> Let's make a ticket and see if any one else reports this issue in the wild. Hopefully it only applies to incognito. IF that is the only issue then I say we can merge this now!

@Atmosfearful good point, i never thought about how incognito interacts with cookies. This is what i see on the page, looks I  can toggle the setting off and on. I'll give it a try.

I think this is an edge case. I was only trying incognito the other day when I was getting errors to see if it was a cookie thing that was causing the problem.

**Comment by jabby09** [comment]
@Atmosfearful I see you merged this. I only tested in chrome. not sure if @ShimonD-KlimaDAO had a chance to review as well.

**Pull request merged**
