### PR TITLE
carbon: Prevent overflow on distribution by project charts

### LINKED ISSUE #1788: [klima data] popup outside of viewport
this page: https://carbon-git-staging-klimadao.vercel.app/details/verra-credits-issued-by-project-type

Issues:
- if you put your mouse in the perfect position
- You trigger a popper to go outside of the viewport which creates a scrollbar, which then causes the chart to reposition, causing it to spazz out
- Slapping an overflow-x: hidden on the <body> element seems to fix it. But double check for charts/tables that need x overflow

### PR DESCRIPTION
**Pull request by biwano**
## Description

Prevent tooltip from overflowing on distribution by project chart and make Edge renderer to resize the chart as a side effect.

## Related Ticket

Resolves #1788

## Changes

| Before  | After  |
|---------|--------|
|img here |img here|

## Checklist

- [X] I have run `npm run build-all` without errors
- [X] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

**Review by 0xemc — CHANGES_REQUESTED** [review]
Looks like this issue is still happening at https://carbon-git-carbon-qa1788-klimadao.vercel.app/details/verra-credits-issued-by-project-type:


https://github.com/KlimaDAO/klimadao/assets/7104689/fbec42d9-b9b8-4f71-84f9-08074f9c2bbe

**Comment by biwano** [comment]
> Looks like this issue is still happening at https://carbon-git-carbon-qa1788-klimadao.vercel.app/details/verra-credits-issued-by-project-type:
> 
>  Screen.Recording.2023-10-31.at.3.17.15.pm.mov

Sorry about that. I made my fix more generic this time.

**Review by sprrwhwk — APPROVED** [review]
Good job on isolating the change to the chart where it's actually broken 👍

**Comment by biwano** [comment]
> Looks like this issue is still happening at https://carbon-git-carbon-qa1788-klimadao.vercel.app/details/verra-credits-issued-by-project-type:
> 
>  Screen.Recording.2023-10-31.at.3.17.15.pm.mov

Can you check again please?

**Pull request merged**
