### PR TITLE
revised approval modal copy for ICR tokens

### LINKED ISSUE #1989: [ICR] ERC1155 Approval Copy changes
The ERC1155 approval mechanism differs from the ERC20 and the approval modal copy should reflect that change as the signing message will be different in MM or other wallets.

The ERC1155 uses setApprovalForAll which allows all amounts for all tokenIds in the contract.

### PR DESCRIPTION
**Pull request by ChazSchmidt**
## Description

Revises the approval modal text to add context regarding ICR tokens setApprovalForAll 

## Related Ticket

Closes #1989

### CODE REVIEW

**Comment by psparacino** [comment]
Content-wise looks fine to me but will wait for @jabby09 to finalize

Just one comment re: PR pointing given that the ICR branch workflow is somewhat convoluted:

This is the base working ICR branch: https://github.com/KlimaDAO/klimadao/pull/1843. Ideally you can point PRs here which I can then merge (the PR branches are updated from this base branch).

This is the FE PR: https://github.com/KlimaDAO/klimadao/pull/2052

Staging will still work; it will just display a note about ICR when no credits yet exist on mainnet. The ICR copy should probably also be conditional.

I'll just copy this over for now, so just a note for the other copy changes

**Comment by jabby09** [comment]
> Content-wise looks fine to me but will wait for @jabby09 to finalize

yea I assigned QA on this one to @0xtapi

**Comment by 0xtapi** [comment]
The content looks fine, but I wonder if we can do a little better context wise. Some thinkings:

1.) The current text might be confusing for a user who doesn't know what ICR credits are:

"The allowance below reflects the sum of all your listings for this specific token. For ICR credit tokens **(what are these tokens?)**, the allowance will reflect the sum of all your ICR token listings **(how do I know whether my listings are ICR token listings?)**."

I assume that by the time ICR credits go live, we would have an accompanying blog post ready (knowing Peter, I'm pretty sure this is a marketing opportunity he would happily take). Could we, in the future, extend the current message with a "Click here to learn more" text that links to that post?

2.) Is it possible to make this text conditional, i.e. it only shows if the user actually intends to list ICR credits? I'm not sure if a user who lists other types of credits would need to be confronted with this message. Could be confusing and cause hesitation.

For now, this current iteration is fine and I'm gonna slap my seal of approval on this PR. But we should consider holding the user's hand a little more in the future once this goes live to make it a 100% smooth, no-confusion experience. After all, Carbonmark exists to make Web3 carbon retirement as easy as possible without leaving any room for head scratching, right?

**Comment by Atmosfearful** [comment]
I am going to pass this to @psparacino since it's pointed at his branch

**Review by 0xemc — APPROVED** [review]

**Review by psparacino — APPROVED** [review]

**Pull request merged**
