### PR TITLE
enhance scrollbar with custom styles

### LINKED ISSUE #276: Improved scroll bars
* [ ] We need custom scroll bars in the dApp, as the Windows OS scroll bar takes up way too much space on short screens.
* [ ] We can reduce the padding in the left hand nav panel between elements to prevent scroll bars from appearing on laptop sized screens

### PR DESCRIPTION
**Pull request by goatsOnDrugs**
## Description
I added a custom scroll bar. it looks slightly different on firefox. I added a dark-gray css var for the bar. Ran this by Onyxmony and he liked it.

## Related Ticket
#276 

Resolves #276 

## Checklist

- [ ] Building the site with `npm run build-site` works without errors
- [ ] Building the app with `npm run build-app` works without errors
- [ ] I formatted JS and TS files with running `npm run format-all`

### CODE REVIEW

**Review by Atmosfearful — APPROVED** [review]
It's amazing how much this improves the look & feel. Should have done this ages ago! thank you!

**Comment by Atmosfearful** [comment]
Looks great on chrome and firefox on windows, can you just look real quick on safari @ShimonD-KlimaDAO ?

**Comment by ShimonD-KlimaDAO** [comment]
I tested Brave, Chrome, Firefox, Safari on Desktop and Mobile (Ubuntu, MacOS, Android) - all look great,except for a few minor notes.

1. Firefox looks a bit different than all the rest (Firefox above, Brave below):
image

2. On Mobile (Chrome), the bar actually got thicker and was already thin before:
https://drive.google.com/file/d/1Edpi1xwP5Ir45QpfwP8n2brG4H13c-VB/view?usp=sharing

**Comment by ShimonD-KlimaDAO** [comment]
3. Microsoft Edge scrollbar is still the old one, but I think our Edge problems are bigger than that (see https://github.com/KlimaDAO/klimadao/issues/434)

image

**Pull request merged**
