### PR TITLE
[retirements] fix project id on retirement page for ICR projects

### LINKED ISSUE #2285: [retirement] ICR retirements are breaking receipt design
ICR projects are breaking our receipt design, see https://www.carbonmark.com/retirements/0x6476edf98bdc5ee62f9d4e4bf8932d69ed685483/44 for example

image

does not seem to be maintaining the equal 2 column layout.

PDF layout seems fine.
[retirement_44_0x6476edf98bdc5ee62f9d4e4bf8932d69ed685483 (3).pdf](https://github.com/KlimaDAO/klimadao/files/14314777/retirement_44_0x6476edf98bdc5ee62f9d4e4bf8932d69ed685483.3.pdf)

### PR DESCRIPTION
**Pull request by sprrwhwk**
## Description

This PR fixes the project id on the retirements page which was showing a long number for ICR projects.

## Related Ticket

Closes #2285

### CODE REVIEW

**Review by jabby09 — CHANGES_REQUESTED** [review]
This fixes the UI issues on the page.

However, the Learn More link is being constructed with the long id and results in 404 page https://carbonmark-git-2285-fix-project-id-on-retirements-page-klimadao.vercel.app/projects/87525131485654382824957055535282281802959500504925522089844996918187118841064-2019

Question:
1. Why is the project description not being included on the receipt?

**Comment by sprrwhwk** [comment]
> This fixes the UI issues on the page.
> 
> However, the Learn More link is being constructed with the long id and results in 404 page https://carbonmark-git-2285-fix-project-id-on-retirements-page-klimadao.vercel.app/projects/87525131485654382824957055535282281802959500504925522089844996918187118841064-2019
> 
> Question:
> 
>     1. Why is the project description not being included on the receipt?

@jabby09 the "learn more"-url is fixed now. I don't understand your question however.

**Comment by jabby09** [comment]
> @jabby09 the "learn more"-url is fixed now. I don't understand your question however.

Non-ICR receipt pages include the project description, so for example https://www.carbonmark.com/retirements/0x6476edf98bdc5ee62f9d4e4bf8932d69ed685483/46

On my ICR receipt pages, the project description you see here (https://www.carbonmark.com/projects/ICR-112-2019) IS NOT being shown on the retirement receipt.

**Comment by jabby09** [comment]
> Non-ICR receipt pages include the project description, so for example https://www.carbonmark.com/retirements/0x6476edf98bdc5ee62f9d4e4bf8932d69ed685483/46
> 
> On my ICR receipt pages, the project description you see here (https://www.carbonmark.com/projects/ICR-112-2019) IS NOT being shown on the retirement receipt.

@sprrwhwk does this make sense now?

**Pull request closed without merging**
