### PR TITLE
Revised fee breakdown

### PR DESCRIPTION
**Pull request by ladytrekker**
Edit: atmos revised this PR & description

## Description

- 'network fees' are no longer calculated and shown to the user. This is because they are included in the per-tonne price.
  - Instead. we give a precise breakdown [in the docs.
](https://docs.carbonmark.com/get-started/understanding-fees-on-carbonmark)
- For fiat payments: 'payment processing fee' is shown to the user. It's calculated with simple subtraction (quoted price minus per-tonne price). This includes the MATIC gas cost (dynamic, variable) and the fixed 20% fee on top of the retirement cost. This is also explained in the docs.
- Added tooltips for both.
- These changes applied to the following paths (preview links attached)
  - [/retire/pools/[token]](https://carbonmark-git-lady-delete-fees-klimadao.vercel.app/projects/VCS-191-2010/retire/pools/bct)
  - [/purchase/pools/[token]](https://carbonmark-git-lady-delete-fees-klimadao.vercel.app/projects/VCS-191-2010/purchase/pools/bct)
  - listings, which we don't have a preview for

This deviates from the most recent design revision because I still found the mixture of 'baked-in' and 'additive' fees too confusing for the user (and difficult to calculate precisely). Now, the line items should always add up to the total cost.

image
image
image

## Related Ticket

Part of this ticket: https://github.com/KlimaDAO/klimadao/issues/1351

## Checklist

- [x] I have run `npm run build-all` without errors
- [x] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

**Comment by Atmosfearful** [comment]
On hold until we get the tooltips from design.

**Review by Atmosfearful — APPROVED** [review]

**Review by jabby09 — COMMENTED** [review]
@Atmosfearful Remind me one more time...is the difference between price per tonne and total cost when using USDC an _estimate_ of **MATIC gas fees**?

Screenshot 2023-08-01 at 9 35 59 AM

**Review by jabby09 — COMMENTED** [review]
@Atmosfearful the Carbonmark fee = 0 is now removed. Assume that was intentional, however, I think we still wanted that to be a callout in support of our zero fees value prop

**Review by jabby09 — COMMENTED** [review]
@Atmosfearful couple of things:

I support the implementation changes compared to the designs but we will need to let @theprofessora know so he can update figma.

The pop up message also deviates from the design, using a blue font colour for the link. Does the blue on grey background pass accessibility?

Screenshot 2023-08-01 at 9 41 29 AM

**Review by jabby09 — COMMENTED** [review]
@Atmosfearful Just want to confirm my understanding the CC payment processing fee:

Example #1: 1 tonne BCT price = 0.66; fee = 0.37; total = 1.03
(so the calc is 1 x 0.66 x 1.2 = 0.79 + gas? So in this example there is 0.24 in gas?)

Example #2 5 tonne BCT price = 0.66; fee = 0.96; total = 4.27
(so the calc is 5 x 0.66 x 1.2 = 3.96 + gas? So in this example there is 0.31 in gas?)

**Comment by theprofessora** [comment]
The blue on the gray does not pass WCAG simple contrast recommendations

**Pull request merged**
