### PR TITLE
Makka / #1906 check for min tonne quantity if usdc

### LINKED ISSUE #1906: [retire] Check on min amount and form error checking
this page https://www.carbonmark.com/projects/VCS-1190-2017/retire/pools/bct

there is only 0.5 tonnes available in this pool
if you change pay with to USDC
and select 0.5 tonnes as the amount
the RETIRE CARBON button remains greyed out
but there is no error message or user feedback

can you look at the code and see what is happening there?
my assumption is that we are checking for a 1 tonne minimum

### PR DESCRIPTION
**Pull request by 0xMakka**
## Description

When a user tries to retire any value under 1 tonne, the "Retire Carbon" button remains greyed out due to the logic around disabling the button to always only check the fiat minimum. 

## Related Ticket

Resolves #1906 

## Checklist

- [X] I have run `npm run build-all` without errors
- [X] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

**Review by jabby09 — COMMENTED** [review]
@0xMakka the ticket actually had a question:
> can you look at the code and see what is happening there?
> my assumption is that we are checking for a 1 tonne minimum

Can you clarify what "fix" you implemented in this PR and what acceptance criteria to test?

Note currently on this [project](https://carbonmark-git-makka-1906-min-amount-check-retire-usdc-klimadao.vercel.app/projects/VCS-1190-2017), I'm seeing Quantity Available now equal to zero. If there is no quantity left I thought we filtered out these listings from the API?

Screenshot 2023-11-23 at 9 24 52 AM

**Comment by 0xMakka** [comment]
> @0xMakka the ticket actually had a question:
> 
> > can you look at the code and see what is happening there?
> > my assumption is that we are checking for a 1 tonne minimum
> 
> Can you clarify what "fix" you implemented in this PR and what acceptance criteria to test?
> 
> Note currently on this [project](https://carbonmark-git-makka-1906-min-amount-check-retire-usdc-klimadao.vercel.app/projects/VCS-1190-2017), I'm seeing Quantity Available now equal to zero. If there is no quantity left I thought we filtered out these listings from the API?
> 
> Screenshot 2023-11-23 at 9 24 52 AM

@jabby09 the code in the PR allows retiring the minimum tonnes of 0.001 as specified in the error message.

Screenshot 2023-11-23 at 13 35 57

Previously if you tried to retire 0.5 tonnes, the button remained greyed out as the check for when the disabled button was using the minimum value from fiat which was always 1. As for the listings shown with 0, this PR didn't make any changes to it. The main change here is enabling the "Retire Carbon" button if the payment method is "usdc" and the value is above the minimum 0.001.

**Review by jabby09 — CHANGES_REQUESTED** [review]
@0xMakka RETIRE CARBON still greyed out when I select 0.001 min which dismisses the error message. I wonder if it is because total cost is $0?
Screenshot 2023-11-23 at 10 33 18 AM

**Comment by 0xMakka** [comment]
> @0xMakka RETIRE CARBON still greyed out when I select 0.001 min which dismisses the error message. I wonder if it is because total cost is $0? Screenshot 2023-11-23 at 10 33 18 AM

@jabby09 apologies the check I was doing was incorrect, I've pushed the changes when you get a chance to retest.

**Review by biwano — APPROVED** [review]
Works great for me

**Pull request merged**
