### PR TITLE
Emc/chore/1693-sdk-package

### PR DESCRIPTION
**Pull request by 0xemc**
## Related Ticket

Resolves #<issue-number>

## Checklist

- [ ] I have run `npm run build-all` without errors
- [ ] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

**Review by 0xMakka — APPROVED** [review]
Great job @0xemc, is this PR still in draft? I went through the changes there and it looks good so I've approved, but not sure if it's fully complete yet?

**Comment by 0xemc** [comment]
> Great job @0xemc, is this PR still in draft? I went through the changes there and it looks good so I've approved, but not sure if it's fully complete yet?

Thanks @0xMakka, Yea we're waiting on a few more project tokens to be created and then we'll remove the hard coded values (for quantity and project).

Thanks for taking a look 🙏

**Comment by 0xemc** [comment]
> Great job @0xemc, is this PR still in draft? I went through the changes there and it looks good so I've approved, but not sure if it's fully complete yet?

Hey @0xMakka thanks for taking a look. This PR has a har dependency on (https://github.com/KlimaDAO/klimadao/pull/1641) this one should come first as it breaks up the risky parts of this shift.

Could you take a look at that one?

**Comment by 0xemc** [comment]
Closing this PR until this piece is re-prioritized

**Pull request closed without merging**
