### PR TITLE
Makka / 1690 remove scrollbar width

### LINKED ISSUE #1690: [contract v2] [mobile] Scroll bar bug
**Describe the bug**
Mobile only: On modals with sufficient vertical length, a scroll bar appears on the right side. At the far right edge of the window, there's a thin black outline of the scroll bar which moves as I scroll up and down the page. Should be invisible.

**To Reproduce**
Open any modal long enough so the user has to scroll, like the filters on the marketplace or the EDIT PROFILE modal in the user profile.

**Expected behavior**
No scroll bar!

**Screenshots**
813690fa-8a8d-43e0-ac48-f41bafc4a5b7

**Smartphone (please complete the following information):**
 - OS: Android 12
 - Browser: MetaMask browser

### PR DESCRIPTION
**Pull request by 0xMakka**
## Description

Remove the scrollbar border on modals

## Related Ticket

Resolves #1690

## Checklist

- [x] I have run `npm run build-all` without errors
- [x] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

**Comment by 0xMakka** [comment]
@Atmosfearful I see in the code you previously added borders on modal scrollbars and left a comment "//Resolve border radius issues by enforcing rounded corners on scroll bars". 

Not sure if the expectation is to continue to show scrollbars on modals though?

**Comment by Atmosfearful** [comment]
Hmm @0xMakka  I think if the modal is scrolling and not the page, we do need a scroll bar to communicate that to the user. Can you speak with @theprofessora to find a better solution (or maybe he agrees we should remove it)

**Comment by 0xMakka** [comment]
> Hmm @0xMakka I think if the modal is scrolling and not the page, we do need a scroll bar to communicate that to the user. Can you speak with @theprofessora to find a better solution (or maybe he agrees we should remove it)

@Atmosfearful yeah, I will speak to @theprofessora to discuss a better alternative to this.

**Comment by 0xMakka** [comment]
> @Atmosfearful @0xMakka is the issue that we think the modal scrollbar looks ugly? If so we can just customize the scrollbar. I think with the nature of some modals (like the filter modal) we definitely have frequent occasions when the modal content is excessively long so we'll need a scrollbar

@theprofessora apologies I'm only replying to this now. Yes, the issue is the scrollbar looks pretty ugly, it's currently just a black border on the scrollbar (it mainly becomes visible on mobile devices). What's your thoughts on removing it completely, or should we still show a scrollbar to the user to indicate the modal is scrollable?

**Comment by 0xemc** [comment]
@0xMakka @Atmosfearful looks like this is no longer an issue?

https://github.com/KlimaDAO/klimadao/issues/1690#issuecomment-1784088461

if so can we please close this PR?

**Comment by Atmosfearful** [comment]
@0xMakka @0xemc still reproducible for me, see my comment here incl. a random fix I seem to have found... https://github.com/KlimaDAO/klimadao/issues/1690#issuecomment-1788166719

**Comment by jabby09** [comment]
@0xMakka is this one ready again for QA and code review?

**Comment by 0xMakka** [comment]
> @0xMakka is this one ready again for QA and code review?

@jabby09 I've tested the suggestion from @Atmosfearful of adding an negative outline-offset and it looks to work locally for me also, so I've pushed the changes.

Before:
Screenshot 2023-11-22 at 22 25 23

After:
Screenshot 2023-11-22 at 22 25 08

**Review by jabby09 — APPROVED** [review]

**Review by 0xemc — APPROVED** [review]
image
 
 I'm getting a little bit of strangeness when viewing in Brave. See above.
 
 Not a big issue so approving anyway

**Comment by 0xMakka** [comment]
> image
> I'm getting a little bit of strangeness when viewing in Brave. See above.
> 
> Not a big issue so approving anyway

Hmm, this is strange as the screenshots I've included are also from Brave.

**Comment by 0xemc** [comment]
> > image
> > I'm getting a little bit of strangeness when viewing in Brave. See above.
> > Not a big issue so approving anyway
> 
> Hmm, this is strange as the screenshots I've included are also from Brave.

Went ahead and merged this for now, if it's only occurting for me not a big deal

**Pull request merged**
