### PR TITLE
make side panel sticky

### LINKED ISSUE #1269: [forms] Make side panel "sticky" on Buy and Retire form pages
On Buy and Retire form pages there is a right side panel where we show Asset and/or Price information. For the price component, this changes in real time as the user interacts with the main form. 

On desktop, as the user scroll the page, the Asset and/or Price information components disappear meaning the user may need to scroll the page to see updated price information before executing the form.

Screenshot 2023-07-02 at 9 58 06 AM

### Requirements

On the following form pages:
- RETIRE from portfolio page
- BUY from pool listing (project details page)
- RETIRE NOW from pool listing (project details page)
- BUY from seller listing (project details page) **NOTE currently not showing in the UI

- [x] Make the Total Price and / or Asset Details component in the right hand side bar sticky to to the view port so when the user scrolls these components say visible on the page
- [x] This is for desktop only

### PR DESCRIPTION
**Pull request by sprrwhwk**
## Description

This PR makes the following side panel sticky so that they stay visible when users scroll down on the retirement page:

- Portfolio page
- Marketplace listing page

## Related Ticket

Resolves #1269 

## Changes

https://github.com/KlimaDAO/klimadao/assets/138768831/c91ea249-3c9b-4081-ba9f-511ff84abf7a

## Checklist

- [x] I have run `npm run build-all` without errors
- [x] I have formatted JS and TS files with `npm run format-all`

### CODE REVIEW

**Review by jabby09 — CHANGES_REQUESTED** [review]
@sprrwhwk confirmed working for RETIRE NOW from pool listing (project details page)

Did not appear to be working for BUY from pool listing (project details page)?

Note I can't test RETIRE from portfolio page currently as we have a profile bug in play but please make sure you apply the side panel sticky to that form as well.

Also apply to BUY from seller listing (project details page) although again I won't be able to test that since all seller listings are removed from the site.

**Comment by jabby09** [comment]
> As Jabby already mentioned, there a couple more views which are rendering similar components:

hi @sprrwhwk 

did the requested review changes above get addressed? Are you ready for additional QA on this ticket?

**Comment by sprrwhwk** [comment]
> > As Jabby already mentioned, there a couple more views which are rendering similar components:
> 
> hi @sprrwhwk
> 
> did the requested review changes above get addressed? Are you ready for additional QA on this ticket?

I don't yet know how to fake a login to test the other views. Maybe I can pair up with someone that knows.

**Comment by jabby09** [comment]
> I don't yet know how to fake a login to test the other views. Maybe I can pair up with someone that knows.

@sprrwhwk I can arrange to have USDC and MATIC sent to your test wallet so you can BUY carbon and RETIRE carbon.

What is your test wallet address?

**Comment by sprrwhwk** [comment]
> > I don't yet know how to fake a login to test the other views. Maybe I can pair up with someone that knows.
> 
> @sprrwhwk I can arrange to have USDC and MATIC sent to your test wallet so you can BUY carbon and RETIRE carbon.
> 
> What is your test wallet address?

0xE3d5afbBeF1214cE6B51937a2E0dE4cfc6Eb82E6

**Comment by sprrwhwk** [comment]
@jabby09 this is ready for review. I have created a follow-up ticket for the remaining two side panels:
#1352

**Review by jabby09 — APPROVED** [review]
Confirmed this is working for RETIRE NOW user journey on a pool listing.

**Review by 0xemc — APPROVED** [review]

**Pull request merged**
