### PR TITLE
Add prettier organise imports (#755)

### LINKED ISSUE #755: Update Retirement Receipt Page
As part of the Fiat 2 Retirement workstream, the [retirement receipt page design](https://www.figma.com/file/gIsDanJUvVwQE4QqSh36Rr/Fiat-2-Retirement?node-id=11%3A9010) was enhanced.

Image

- [ ] Include new CTA button in top retirement info section called "Claim Your Pledge Dashboard".
- [x] Remove current social share icons.
- [x] Include new section called "Share Your Impact" (note new location of social share icons).

### LINKED ISSUE #757: add prettier-plugin-organize-imports
@MColl92 @0xAeterno Indeed I've used that on another project and it worked flawlessly, I'm all for it.
There are a lot of big open PRs right now that I'd like to get closed up before I create too many change conflicts though!

_Originally posted by @Atmosfearful in https://github.com/KlimaDAO/klimadao/pull/742#discussion_r1003793139_

### PR DESCRIPTION
**Pull request by 0xemc**
## Description

Adds the following packages:
* https://www.npmjs.com/package/prettier-plugin-organize-imports
* https://www.npmjs.com/package/concurrently

New script `build-all` to quickly execute build check of all workspaces

## Related Ticket

Resolves #757 

## Checklist

- [x] Building the site with `npm run build-site` works without errors
- [x] Building the app with `npm run build-app` works without errors
- [x] I formatted JS and TS files with running `npm run format-all`

### CODE REVIEW

**Review by ladytrekker — APPROVED** [review]
Thanks for taking care of this.

This also applies when saving a file, right? (if autosave is enabled in the editor)

Sidenote: The linked ticket 755 in the PR description does not match.

**Comment by 0xemc** [comment]
> Thanks for taking care of this.
> 
> This also applies when saving a file, right? (if autosave is enabled in the editor)
> 
> Sidenote: The linked ticket 755 in the PR description does not match.

Ah yes, updated to #757 

Also yes it will automatically format on save too (if you have that enabled in vscode).

**Review by Atmosfearful — APPROVED** [review]
Very nice, I just want to get our three big PRs merged before I merge this and create more conflicts.

Question- as a prettier plugin, this means it should auto-sort on save in VSCode as well correct?

**Review by Atmosfearful — CHANGES_REQUESTED** [review]
ah, please add a line to the repo README describing this build-all command

**Comment by 0xemc** [comment]
>..this means it should auto-sort on save in VSCode as well correct? It will yea

Yep it will, it's create for PR conflicts because you just accept both and then when you save it automatically removes the unused imports.

**Comment by 0xemc** [comment]
> ah, please add a line to the repo README describing this build-all command

Good point, done. And updated the PR template too (hope that's ok..)

**Comment by 0xemc** [comment]
> ah, please add a line to the repo README describing this build-all command

@Atmosfearful this should be taken care of now. Let me know if it needs more detail.

**Comment by 0xemc** [comment]
> @0xemc if you can rebase/merge staging and address the conflicts then this should be good to go :)

No worries, done

**Comment by 0xemc** [comment]
@Atmosfearful this should be ready to go now

**Review by Atmosfearful — APPROVED** [review]

**Pull request merged**
